Add support for QNX Neutrino
flba-eb/rust_net2-rs pull request #1
Opened 2023-01-14 14:14 UTC by flba-eb

@gh-tr Please have a look; I needed more modifications than the original patch.

2023-01-16 16:18 UTC, gh-tr requested changes

2023-01-16 16:18 UTC, gh-tr commented on src/ext.rs
> +    if #[cfg(any(target_os = "macos", target_os = "ios", target_os = "nto"))] {
On line 717, it appears that the time in seconds is being passed in as a c_int:

`if let Some(dur) = keepalive {
            try!(set_opt(self.as_sock(), v(IPPROTO_TCP), KEEPALIVE_OPTION,
                        (dur / 1000) as c_int));
        }
`

On line 71, it uses the payload type:

`pub fn set_opt<T: Copy>(sock: Socket, opt: c_int, val: c_int,
                       payload: T) -> io::Result<()> {
    unsafe {
        let payload = &payload as *const T as *const c_void;
        try!(::cvt(setsockopt(sock, opt, val, payload as *const _,
                              mem::size_of::<T>() as socklen_t)));
    }
    Ok(())
`

I think this value needs to be a timeval: https://www.qnx.com/developers/docs/7.1/#com.qnx.doc.neutrino.lib_ref/topic/g/getsockopt.html#getsockopt__TCP_KEEPALIVE

2023-06-14 14:02 UTC, flba-eb commented on src/ext.rs
> +    if #[cfg(any(target_os = "macos", target_os = "ios", target_os = "nto"))] {
Should be fine.

2023-06-14 14:36 UTC, flba-eb commented
https://github.com/deprecrated/net2-rs/pull/115

2023-06-14 14:36 UTC, closed without merging